# Generated by Django 6.0.4 on 2026-05-01 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='جمع کرایه')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات (9%)')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قابل پرداخت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('paid', 'پرداخت شده'), ('overdue', 'سررسید گذشته'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer', verbose_name='مشتری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('income', 'دریافت'), ('expense', 'پرداخت')], max_length=10, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('check', 'چک'), ('card', 'کارتخوان'), ('transfer', 'انتقال بانکی')], max_length=20, verbose_name='نوع پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع (شماره چک/رسید)')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='مشتری')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.driver', verbose_name='راننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='فاکتور مربوطه')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='عدد 1 تا 12', verbose_name='ماه')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حقوق پایه')),
                ('trip_count', models.IntegerField(default=0, verbose_name='تعداد سفر')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل مبلغ کرایه\u200cها')),
                ('driver_share', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سهم راننده (30%)')),
                ('bonuses', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='پاداش')),
                ('deductions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کسورات')),
                ('net_payable', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قابل پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='orders.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'حقوق راننده',
                'verbose_name_plural': 'حقوق رانندگان',
                'unique_together': {('driver', 'month', 'year')},
            },
        ),
    ]
