# Generated by Django 6.0.4 on 2026-05-02 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='عملیات')),
                ('page', models.CharField(max_length=200, verbose_name='صفحه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ دسترسی',
                'verbose_name_plural': 'لاگ\u200cهای دسترسی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر کل'), ('manager', 'مدیر'), ('accountant', 'حسابدار'), ('dispatcher', 'مسئول تخصیص بار'), ('viewer', 'بازدیدکننده')], default='viewer', max_length=20)),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='مدیریت مشتریان')),
                ('can_manage_drivers', models.BooleanField(default=False, verbose_name='مدیریت رانندگان')),
                ('can_manage_vehicles', models.BooleanField(default=False, verbose_name='مدیریت خودروها')),
                ('can_manage_orders', models.BooleanField(default=False, verbose_name='مدیریت سفارشات')),
                ('can_manage_finance', models.BooleanField(default=False, verbose_name='مدیریت مالی')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='مشاهده گزارشات')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='مدیریت کاربران')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نقش کاربری',
                'verbose_name_plural': 'نقش\u200cهای کاربری',
            },
        ),
    ]
