# Generated by Django 6.0.4 on 2026-05-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='عرض مرکز')),
                ('center_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='طول مرکز')),
                ('radius', models.IntegerField(default=100, verbose_name='شعاع (متر)')),
                ('polygon_coords', models.TextField(blank=True, help_text='JSON format: [[lat,lng], [lat,lng], ...]', verbose_name='مختصات چند ضلعی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منطقه جغرافیایی',
                'verbose_name_plural': 'مناطق جغرافیایی',
            },
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('start_location', models.CharField(max_length=500, verbose_name='موقعیت شروع')),
                ('end_location', models.CharField(blank=True, max_length=500, null=True, verbose_name='موقعیت پایان')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مسافت کل (km)')),
                ('total_duration', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver', verbose_name='راننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_history', to='orders.order', verbose_name='سفارش')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'تاریخچه سفر',
                'verbose_name_plural': 'تاریخچه سفرها',
            },
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speeding', 'سرعت غیرمجاز'), ('off_route', 'خروج از مسیر'), ('geofence_enter', 'ورود به منطقه'), ('geofence_exit', 'خروج از منطقه'), ('idle', 'توقف طولانی'), ('emergency', 'وضعیت اضطراری')], max_length=20, verbose_name='نوع هشدار')),
                ('message', models.TextField(verbose_name='پیام هشدار')),
                ('location', models.CharField(max_length=500, verbose_name='موقعیت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='برطرف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برطرف شدن')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش مرتبط')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='orders.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'هشدار خودرو',
                'verbose_name_plural': 'هشدارهای خودرو',
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='طول جغرافیایی')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='سرعت (km/h)')),
                ('direction', models.IntegerField(blank=True, null=True, verbose_name='جهت (درجه)')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دقت (متر)')),
                ('location_time', models.DateTimeField(verbose_name='زمان موقعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت در سیستم')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver', verbose_name='راننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش جاری')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='orders.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'موقعیت خودرو',
                'verbose_name_plural': 'موقعیت خودروها',
                'ordering': ['-location_time'],
                'indexes': [models.Index(fields=['vehicle', '-location_time'], name='tracking_ve_vehicle_5ec2f6_idx'), models.Index(fields=['order'], name='tracking_ve_order_i_069dfd_idx')],
            },
        ),
    ]
