# Generated by Django 6.0.4 on 2026-05-01 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('license_number', models.CharField(max_length=20, verbose_name='شماره گواهینامه')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت/شخص')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی/اقتصادی')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سقف اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('origin', models.CharField(max_length=300, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=300, verbose_name='مقصد')),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cargo_type', models.CharField(max_length=100, verbose_name='نوع بار')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='وزن (تن)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='حجم (مترمکعب)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کرایه (تومان)')),
                ('advance_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='پیش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تخصیص'), ('assigned', 'تخصیص داده شده'), ('loading', 'در حال بارگیری'), ('in_transit', 'در مسیر'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('pickup_date', models.DateTimeField(verbose_name='زمان بارگیری')),
                ('expected_delivery', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخمینی تحویل')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='زمان واقعی تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer', verbose_name='مشتری')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('waybill', 'بارنامه'), ('insurance', 'بیمه نامه'), ('customs', 'مدارک گمرکی'), ('invoice', 'فاکتور'), ('other', 'سایر')], max_length=20, verbose_name='نوع سند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سند')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='فایل سند')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order', verbose_name='سفارش')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پلاک')),
                ('model', models.CharField(max_length=50, verbose_name='مدل')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ظرفیت (تن)')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver', verbose_name='راننده فعلی')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.vehicle', verbose_name='خودرو'),
        ),
    ]
